apiVersion: v1
kind: ConfigMap
metadata:
  name: x-ui-pro-config
  namespace: x-ui-pro
  labels:
    app.kubernetes.io/name: x-ui-pro
    app.kubernetes.io/part-of: x-ui-pro
data:
  TZ: "UTC"
  LOG_LEVEL: "info"
  XRAY_VMESS_AEAD_FORCED: "false"
  PGSSLMODE: "disable"
