apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: x-ui-pro-data
  namespace: x-ui-pro
  labels:
    app.kubernetes.io/name: x-ui-pro
    app.kubernetes.io/part-of: x-ui-pro
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: x-ui-pro-certs
  namespace: x-ui-pro
  labels:
    app.kubernetes.io/name: x-ui-pro
    app.kubernetes.io/part-of: x-ui-pro
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
