apiVersion: v1
kind: Secret
metadata:
  name: x-ui-pro-secret
  namespace: x-ui-pro
  labels:
    app.kubernetes.io/name: x-ui-pro
    app.kubernetes.io/part-of: x-ui-pro
type: Opaque
stringData:
  JWT_SECRET: "change-this-to-a-random-64-char-string"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "admin"
  DB_PATH: "/etc/x-ui/x-ui.db"
