apiVersion: v1
kind: Service
metadata:
  name: x-ui-pro
  namespace: x-ui-pro
  labels:
    app.kubernetes.io/name: x-ui-pro
    app.kubernetes.io/part-of: x-ui-pro
spec:
  type: ClusterIP
  ports:
    - name: webui
      port: 2053
      targetPort: webui
      protocol: TCP
    - name: xray-api
      port: 10085
      targetPort: xray-api
      protocol: TCP
  selector:
    app: x-ui-pro
